### class(day-34:2-7-20)
### Importing Libraries:

In [1]:
import pandas as pd
import numpy as np

### Reading the data:

In [2]:
data = pd.read_csv("https://raw.githubusercontent.com/Mounika-Kajjam/Datasets/master/spam.csv",encoding='latin-1')
data.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [3]:
data.shape

(5572, 5)

### splitting the data:### 

In [4]:
# split the data
# 80% of the data will be in training data  20% of the data will be in testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(data.v2,data.v1,test_size = 0.2)

In [5]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)


(4457,)
(4457,)
(1115,)
(1115,)


### initialising count vectorizer:

In [7]:
# count vectorizer
from sklearn.feature_extraction.text import CountVectorizer

# creating an object for countvectorizer
count_vect = CountVectorizer()

### To get the feature names:

In [8]:
# generate the word counts for the words in the documents
word_count_vector = count_vect.fit(x_train)

# to get the feature names
word_count_vector.get_feature_names()

['00',
 '000',
 '000pes',
 '008704050406',
 '0089',
 '01223585236',
 '01223585334',
 '0125698789',
 '02',
 '0207',
 '02072069400',
 '02073162414',
 '02085076972',
 '021',
 '03',
 '04',
 '0430',
 '05',
 '050703',
 '0578',
 '06',
 '07',
 '07008009200',
 '07046744435',
 '07090201529',
 '07099833605',
 '07123456789',
 '07732584351',
 '07734396839',
 '07742676969',
 '07753741225',
 '0776xxxxxxx',
 '07781482378',
 '07786200117',
 '077xxx',
 '078',
 '07801543489',
 '07808',
 '07808726822',
 '07815296484',
 '07821230901',
 '078498',
 '07880867867',
 '0789xxxxxxx',
 '07946746291',
 '07973788240',
 '07xxxxxxxxx',
 '08',
 '0800',
 '08000407165',
 '08000776320',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08002988890',
 '0808',
 '08081263000',
 '08081560665',
 '0825',
 '0844',
 '08448350055',
 '0845',
 '08450542832',
 '08452810071',
 '08452810073',
 '08452810075over18',
 '0870',
 '08700435505150p',
 '08700469649',
 '087006211701

### Transforming the data:

In [25]:
doc_array = word_count_vector.transform(x_train)
doc_array


<4457x7646 sparse matrix of type '<class 'numpy.int64'>'
	with 58839 stored elements in Compressed Sparse Row format>

In [26]:
# converting to a array
doc_array = word_count_vector.transform(x_train).toarray()
doc_array

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

### Specifying column names:

In [28]:
# converting the array into a dataframe
pd.DataFrame(doc_array)

0     1     2     3     4     5     6     7     8     9     ...  7636  \
0        0     0     0     0     0     0     0     0     0     0  ...     0   
1        0     0     0     0     0     0     0     0     0     0  ...     0   
2        0     0     0     0     0     0     0     0     0     0  ...     0   
3        0     0     0     0     0     0     0     0     0     0  ...     0   
4        0     0     0     0     0     0     0     0     0     0  ...     0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
4452     0     0     0     0     0     0     0     0     0     0  ...     0   
4453     0     0     0     0     0     0     0     0     0     0  ...     0   
4454     0     0     0     0     0     0     0     0     0     0  ...     0   
4455     0     0     0     0     0     0     0     0     0     0  ...     0   
4456     0     0     0     0     0     0     0     0     0     0  ...     0   

      7637  7638  7639  7640  7641  7642  7643  7644  7645  
0        0     0     0     0     0     0     0     0     0  
1        0     0     0     0     0     0     0     0     0  
2        0     0     0     0     0     0     0     0     0  
3        0     0     0     0     0     0     0     0     0  
4        0     0     0     0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
4452     0     0     0     0     0     0     0     0     0  
4453     0     0     0     0     0     0     0     0     0  
4454     0     0     0     0     0     0     0     0     0  
4455     0     0     0     0     0     0     0     0     0  
4456     0     0     0     0     0     0     0     0     0  

[4457 rows x 7646 columns]

In [29]:
feature_matrix = pd.DataFrame(doc_array,columns= word_count_vector.get_feature_names())
feature_matrix

00  000  000pes  008704050406  0089  01223585236  01223585334  \
0      0    0       0             0     0            0            0   
1      0    0       0             0     0            0            0   
2      0    0       0             0     0            0            0   
3      0    0       0             0     0            0            0   
4      0    0       0             0     0            0            0   
...   ..  ...     ...           ...   ...          ...          ...   
4452   0    0       0             0     0            0            0   
4453   0    0       0             0     0            0            0   
4454   0    0       0             0     0            0            0   
4455   0    0       0             0     0            0            0   
4456   0    0       0             0     0            0            0   

      0125698789  02  0207  ...  ó_  û_  û_thanks  ûªm  ûªt  ûªve  ûï  \
0              0   0     0  ...   0   0         0    0    0     0   0   
1              0   0     0  ...   0   0         0    0    0     0   0   
2              0   0     0  ...   0   0         0    0    0     0   0   
3              0   0     0  ...   0   0         0    0    0     0   0   
4              0   0     0  ...   0   0         0    0    0     0   0   
...          ...  ..   ...  ...  ..  ..       ...  ...  ...   ...  ..   
4452           0   0     0  ...   0   0         0    0    0     0   0   
4453           0   0     0  ...   0   0         0    0    0     0   0   
4454           0   0     0  ...   0   0         0    0    0     0   0   
4455           0   0     0  ...   0   0         0    0    0     0   0   
4456           0   0     0  ...   0   0         0    0    0     0   0   

      ûïharry  ûò  ûówell  
0           0   0       0  
1           0   0       0  
2           0   0       0  
3           0   0       0  
4           0   0       0  
...       ...  ..     ...  
4452        0   0       0  
4453        0   0       0  
4454        0   0       0  
4455        0   0       0  
4456        0   0       0  

[4457 rows x 7646 columns]

In [10]:
# pd.set_option('display.max_rows',none)

### class(day-35:3-7-20)

In [11]:
# TFIDF Vectorizer
# Import TfIDF Vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize and object for the TFIDF Vectorizer
tfidf = TfidfVectorizer()

In [12]:

# apply the tfidf to the data(x_train)
x_train_transformed = tfidf.fit_transform(x_train)
x_train_transformed


<4457x7646 sparse matrix of type '<class 'numpy.float64'>'
	with 58839 stored elements in Compressed Sparse Row format>

In [13]:
x_test_transformed = tfidf.transform(x_test)
x_test_transformed

<1115x7646 sparse matrix of type '<class 'numpy.float64'>'
	with 13982 stored elements in Compressed Sparse Row format>

In [14]:
# Feature Names
tfidf.get_feature_names()

['00',
 '000',
 '000pes',
 '008704050406',
 '0089',
 '01223585236',
 '01223585334',
 '0125698789',
 '02',
 '0207',
 '02072069400',
 '02073162414',
 '02085076972',
 '021',
 '03',
 '04',
 '0430',
 '05',
 '050703',
 '0578',
 '06',
 '07',
 '07008009200',
 '07046744435',
 '07090201529',
 '07099833605',
 '07123456789',
 '07732584351',
 '07734396839',
 '07742676969',
 '07753741225',
 '0776xxxxxxx',
 '07781482378',
 '07786200117',
 '077xxx',
 '078',
 '07801543489',
 '07808',
 '07808726822',
 '07815296484',
 '07821230901',
 '078498',
 '07880867867',
 '0789xxxxxxx',
 '07946746291',
 '07973788240',
 '07xxxxxxxxx',
 '08',
 '0800',
 '08000407165',
 '08000776320',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08002988890',
 '0808',
 '08081263000',
 '08081560665',
 '0825',
 '0844',
 '08448350055',
 '0845',
 '08450542832',
 '08452810071',
 '08452810073',
 '08452810075over18',
 '0870',
 '08700435505150p',
 '08700469649',
 '087006211701

In [15]:
# position of the words in the sparse matrix
tfidf.vocabulary_

{'each': 2489,
 'moment': 4527,
 'in': 3607,
 'day': 2163,
 'has': 3321,
 'its': 3732,
 'own': 4998,
 'value': 7137,
 'morning': 4552,
 'brings': 1489,
 'hope': 3463,
 'afternoon': 842,
 'faith': 2742,
 'evening': 2646,
 'luv': 4231,
 'night': 4739,
 'rest': 5678,
 'wish': 7429,
 'find': 2841,
 'them': 6730,
 'all': 896,
 'today': 6843,
 'good': 3158,
 'best': 1305,
 'msg': 4580,
 'it': 3726,
 'hard': 3312,
 'to': 6836,
 'be': 1252,
 'with': 7436,
 'person': 5122,
 'when': 7371,
 'know': 3931,
 'that': 6717,
 'one': 4902,
 'more': 4548,
 'step': 6386,
 'foward': 2954,
 'will': 7407,
 'make': 4291,
 'fall': 2747,
 'love': 4195,
 'amp': 928,
 'back': 1179,
 'can': 1608,
 'ruin': 5775,
 'ur': 7094,
 'friendship': 2990,
 'omw': 4897,
 'tampa': 6618,
 'from': 3001,
 'west': 7356,
 'palm': 5020,
 'you': 7591,
 'hear': 3353,
 'what': 7364,
 'happened': 3304,
 'oops': 4919,
 'got': 3175,
 'bit': 1350,
 'sent': 5935,
 'me': 4371,
 'email': 2559,
 'id': 3559,
 'soon': 6236,
 'free': 2970,
 'entr

In [16]:
# Idf of the terms
tfidf.idf_

array([7.09987042, 6.31141306, 8.70930833, ..., 8.70930833, 7.61069604,
       8.70930833])

In [17]:

# Apply the naive Bayes Algorithm
# Import BernNB
from sklearn.naive_bayes import BernoulliNB
# creating an object for BerNB
model_BernNB = BernoulliNB()

In [19]:

# Applying the algorithm to the data
# objectName.fit(Input,Output)
model_BernNB.fit(x_train_transformed, y_train)


BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [20]:
 
# prediction on test data
# SYNTAX: objectname.predict(InputValues)
y_test_pred = model_BernNB.predict(x_test_transformed)

In [21]:

# compare the actual values(y_test) with predicted values(y_test_pred)
from sklearn.metrics import confusion_matrix,classification_report
confusion_matrix(y_test,y_test_pred)


array([[958,   0],
       [ 27, 130]], dtype=int64)

In [22]:

print(classification_report(y_test,y_test_pred))


              precision    recall  f1-score   support

         ham       0.97      1.00      0.99       958
        spam       1.00      0.83      0.91       157

    accuracy                           0.98      1115
   macro avg       0.99      0.91      0.95      1115
weighted avg       0.98      0.98      0.97      1115



### Testing for new message

In [23]:
# test a single message --> Spam or Ham
new_message = pd.Series('Last few days to collect the free entry passes with 40% discount')
#calculate tfidf values for the new message
new_message_transformed = tfidf.transform(new_message)

In [24]:
# predict the new message
model_BernNB.predict(new_message_transformed)

array(['ham'], dtype='<U4')